## from .baseComp import BaseR, BaseC, BaseI, BaseGY, BaseTF, BaseESource, BaseFSource, BaseEDetect, BaseFDetect, BaseENode, BaseFNode

componentMap = [
    {
        "type": "base-r",
        "name": "阻抗元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "baseSystem/base-r",
        "params": [{"name": "阻值", "key": "R", "value": 1}],
        "componentName": "baseSystem/BaseR",
    },{
        "type": "base-c",
        "name": "容抗元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "baseSystem/base-c",
        "params": [{"name": "电容", "key": "C", "value": 1}],
        "componentName": "baseSystem/BaseC",
    },{
        "type": "base-i",
        "name": "惯性元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "baseSystem/base-i",
        "params": [{"name": "惯量", "key": "J", "value": 1}],
        "componentName": "baseSystem/BaseI",
    },{
        "type": "base-gy",
        "name": "旋转元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 1, "min": 1},
        "icon": "baseSystem/base-gy",
        "params": [{"name": "势流旋转率", "key": "r_e", "value": 1}],
        "componentName": "baseSystem/BaseGY",
    },{
        "type": "base-tf",
        "name": "变换元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 1, "min": 1},
        "icon": "baseSystem/base-tf",
        "params": [{"name": "势变化率", "key": "r_e", "value": 1}],
        "componentName": "baseSystem/BaseTF",
    },{
        "type": "base-e-source",
        "name": "势源元件",
        "inCount": {"max": 0, "min": 0},
        "outCount": {"max": 1, "min": 1},
        "icon": "baseSystem/base-e-source",
        "params": [{"name": "势源值", "key": "source_e2", "value": 1}],
        "componentName": "baseSystem/BaseESource",
    },{
        "type": "base-f-source",
        "name": "流源元件",
        "inCount": {"max": 0, "min": 0},
        "outCount": {"max": 1, "min": 1},
        "icon": "baseSystem/base-f-source",
        "params": [{"name": "流源值", "key": "source_f2", "value": 1}],
        "componentName": "baseSystem/BaseFSource",
    },{
        "type": "base-e-detect",
        "name": "势探测器",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "baseSystem/base-e-detect",
        "params": [],
        "componentName": "baseSystem/BaseEDetect",
    },{
        "type": "base-f-detect",
        "name": "流探测器",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "baseSystem/base-f-detect",
        "params": [],
        "componentName": "baseSystem/BaseFDetect",
    },{
        "type": "base-e-node",
        "name": "共势结",
        "inCount": {"max": -1, "min": 1},
        "outCount": {"max": -1, "min": 1},
        "icon": "baseSystem/base-e-node",
        "params": [],
        "componentName": "baseSystem/BaseENode",
    },{
        "type": "base-f-node",
        "name": "共流结",
        "inCount": {"max": -1, "min": 1},
        "outCount": {"max": -1, "min": 1},
        "icon": "baseSystem/base-f-node",
        "params": [],
        "componentName": "baseSystem/BaseFNode",
    },{
        "type": "base-global-detect",
        "name": "全局变量探测器",
        "inCount": {"max": 0, "min": 0},
        "outCount": {"max": 0, "min": 0},
        "icon": "baseSystem/base-global-detect",
        "params": [{"name": "全局变量", "key": "global", "value": "L", "isGlobal": True}],
    }]

heatMap=[ 
    ## 一次侧-反应堆
    {
        "type": "heat-r-cooling",
        "name": "一次侧-反应堆近端耗散元件",
        "inCount": {"max": 3, "min": 3},
        "outCount": {"max": 3, "min": 3},
        "icon": "heatmodule/heat-r-cooling",
        "params": [{"name": "工质比热容", "key": "C_l", "value": 4180},
                   {"name": "反应堆比热容", "key": "C_r", "value": 1170},
                   {"name": "反应堆质量", "key": "M_r", "value": 1000},
                   {"name": "一次侧-反应堆管道导纳系数", "key": "R_daona", "value": 0.1},
                   {"name": "一次侧-反应堆金属壁等效传热面积", "key": "H1", "value": 1262},
                   {"name": "一次侧-反应堆金属壁等效传热系数", "key": "K", "value": 33129},
                   ],
        "componentName": "coolingModule/HeatR_Cooling",
    }, {
        "type": "heat-c1-cooling",
        "name": "一次侧-反应堆容性元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "heatmodule/heat-c1-cooling",
        "params": [{"name": "一次侧-反应堆金属壁等比热容", "key": "Cm", "value": 15503.67},
                   {"name": "一次侧-反应堆金属壁等效质量", "key": "Mm", "value": 10000}, ],
        "componentName": "coolingModule/HeatC1_Cooling",
    }, {
        "type": "heat-c2-cooling",
        "name": "一次侧-反应堆远端容性元件",
        "inCount": {"max": 2, "min": 2},
        "outCount": {"max": 0, "min": 0},
        "icon": "heatmodule/heat-c2-cooling",
        "params": [{"name": "一次侧-反应堆管道等效体积", "key": "V", "value": 10000},
                   {"name": "工质饱和密度", "key": "rho_map", "isFunc": True},
                   {"name": "工质饱和比焓", "key": "h_map", "isFunc": True},
                   ],
        "componentName": "coolingModule/HeatC2_Cooling",
    },  {
        "type": "heat-cooling-source",
        "name": "反应堆流源元件",
        "inCount": {"max": 0, "min": 0},
        "outCount": {"max": 1, "min": 1},
        "icon": "heatmodule/heat-cooling-source",
        "params": [{"name": "反应热流量", "key": "source_f211", "value": 100},
                   ],
        "componentName": "coolingModule/HeatCoolingSource",
    }, 

    ## 一次侧
    {
        "type": "heat-memory",
        "name": "饱和延迟元件",
        "inCount": {"max": 2, "min": 2},
        "outCount": {"max": 2, "min": 2},
        "icon": "heatmodule/heat-memory",
        "params": [{"name": "初始温度", "key": "init_T", "value": 20},
                   {"name": "初始压强", "key": "init_P", "value": 100000},
                   {"name": "工质饱和比焓", "key": "h_map", "isFunc": True},
                   ],
        "componentName": "primeModule/HeatMemeory",
    }, {
        "type": "heat-r-prime",
        "name": "一次侧近端耗散元件",
        "inCount": {"max": 2, "min": 2},
        "outCount": {"max": 3, "min": 3},
        "icon": "heatmodule/heat-r-prime",
        "params": [{"name": "比热容", "key": "C_l", "value": 4180},
                   {"name": "导纳系数", "key": "R_daona", "value": 0.1},
                   {"name": "一次侧金属壁等效传热面积", "key": "H1", "value": 1262},
                   {"name": "一次侧金属壁等效传热系数", "key": "K", "value": 33129},
                   ],
        "componentName": "primeModule/HeatR_Prime",
    }, {
        "type": "heat-c1-prime",
        "name": "一次侧-金属壁容性元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "heatmodule/heat-c1-prime",
        "params": [{"name": "一次侧金属壁等比热容", "key": "Cm", "value": 3850},
                   {"name": "一次侧金属壁等效质量", "key": "Mm", "value": 15503.67}, 
                   ],
        "componentName": "primeModule/HeatC1_Prime",
    }, {
        "type": "heat-c2-prime",
        "name": "一次侧远端容性元件",
        "inCount": {"max": 2, "min": 2},
        "outCount": {"max": 0, "min": 0},
        "icon": "heatmodule/heat-c2-prime",
        "params": [{"name": "一次侧管道等效体积", "key": "V", "value": 10000},
                   {"name": "饱和密度", "key": "rho_map", "isFunc": True},
                   {"name": "饱和比焓", "key": "h_map", "isFunc": True},
                   ],
        "componentName": "primeModule/HeatC2_Prime",
    },  {
        "type": "heat-prime-source",
        "name": "一次侧流源元件",
        "inCount": {"max": 0, "min": 0},
        "outCount": {"max": 2, "min": 2},
        "icon": "heatmodule/heat-prime-source",
        "params": [{"name": "入口工质流量源", "key": "source_f211", "value": 100},
                   {"name": "饱和比焓", "key": "K", "isFunc": True},
                   ],
        "componentName": "primeModule/HeatPrimeSource",
    }, 

    ## 下降段
    {
        "type": "heat-alpha-des",
        "name": "下降段近端汇流元件",
        "inCount": {"max": 4, "min": 4},
        "outCount": {"max": 2, "min": 2},
        "icon": "heatmodule/heat-alpha-des",
        "params": [{"name": "饱和比焓", "key": "h_map", "isFunc": True},
                   ],
        "componentName": "descentModule/HeatAlpha_Des",
    }, {
        "type": "heat-rc-des",
        "name": "下降段过程耗散元件",
        "inCount": {"max": 2, "min": 2},
        "outCount": {"max": 2, "min": 2},
        "icon": "heatmodule/heat-rc-des",
        "params": [{"name": "管壁摩擦系数", "key": "cf", "value": 0.3},
                   {"name": "下降段阻尼", "key": "cchy", "value": 0.1},
                   {"name": "重力系数", "key": "g", "value": 9.8},
                   {"name": "下降段管道截面积", "key": "S", "value": 50},
                   {"name": "下降段水位", "key": "Ld", "value": "Ld", "isGlobal": True},
                   {"name": "饱和蒸汽压", "key": "Pg_map", "isFunc": True},
                   {"name": "饱和密度", "key": "rho_map", "isFunc": True},
                   {"name": "饱和比焓", "key": "h_map", "isFunc": True},
                   ],
        "componentName": "descentModule/HeatRC_Des",
    }, {
        "type": "heat-inject-des-source",
        "name": "下降段给水源元件",
        "inCount": {"max": 0, "min": 0},
        "outCount": {"max": 2, "min": 2},
        "icon": "heatmodule/heat-inject-des-source",
        "params": [{"name": "给水温度", "key": "source_e210", "value": 20},
                   {"name": "给水流量", "key": "source_f211", "value": 100},
                   ],
        "componentName": "descentModule/HeatInjetDesSource",
    }, 

    ## 沸腾段
    {
        "type": "heat-rc-boil",
        "name": "沸腾段近端耗散元件",
        "inCount": {"max": 3, "min": 3},
        "outCount": {"max": 4, "min": 4},
        "icon": "heatmodule/heat-rc-boil",
        "params": [{"name": "沸腾段总长", "key": "Lssg", "value": 20},
                   {"name": "沸腾段阻尼", "key": "cchy", "value": 0.0105},
                   {"name": "重力系数", "key": "g", "value": 9.8},
                   {"name": "沸腾段管道截面积", "key": "S", "value": 100},
                   {"name": "过冷段水位", "key": "L1", "value": "L1", "isGlobal": True},
                   {"name": "沸腾段金属壁传热", "key": "Q_boil", "value": "Q_boil", "isGlobal": True},
                   {"name": "气体质量分数", "key": "x", "value": "x", "isGlobal": True},
                   {"name": "饱和密度", "key": "rho_map", "isFunc": True},
                   {"name": "饱和蒸汽密度", "key": "rho_g_map", "isFunc": True},
                   {"name": "饱和温度", "key": "Ts_map", "isFunc": True},
                   {"name": "饱和比焓", "key": "h_map", "isFunc": True},
                   {"name": "饱和蒸汽比焓", "key": "h_g_map", "isFunc": True},
                   ],
        "componentName": "boilModule/HeatRC_Boil",
    }, {
        "type": "heat-r-boil",
        "name": "沸腾段-金属壁阻性元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "heatmodule/heat-r-boil",
        "params": [{"name": "过冷段水位", "key": "L1", "value": "L1", "isGlobal": True},
                   {"name": "沸腾段总长", "key": "Lssg", "value": 20},
                   {"name": "沸腾段金属壁等效传热面积", "key": "Hssg", "value": 1262},
                   {"name": "沸腾段金属壁传热系数", "key": "K2", "value": 30000},
                   ],
        "componentName": "boilModule/HeatR_Boil",
    },

    ## 过冷段
    {
        "type": "heat-rc-supercooling",
        "name": "过冷段近端耗散元件",
        "inCount": {"max": 3, "min": 3},
        "outCount": {"max": 4, "min": 4},
        "icon": "heatmodule/heat-rc-supercooling",
        "params": [{"name": "沸腾段总长", "key": "Lssg", "value": 20},
                   {"name": "过冷段阻尼", "key": "cchy", "value": 0.0105},
                   {"name": "重力系数", "key": "g", "value": 9.8},
                   {"name": "过冷段管道截面积", "key": "S", "value": 100},
                   {"name": "水位修正系数", "key": "neta", "value": 1},
                   {"name": "过冷段水位", "key": "L1", "value": "L1", "isGlobal": True},
                   {"name": "沸腾段金属壁传热", "key": "Q_boil", "value": "Q_boil", "isGlobal": True},
                   {"name": "饱和密度", "key": "rho_map", "isFunc": True},
                   {"name": "饱和温度", "key": "Ts_map", "isFunc": True},
                   {"name": "饱和比焓", "key": "h_map", "isFunc": True},
                   ],
        "componentName": "supercoolingModule/HeatRC_Supercooling",
    }, {
        "type": "heat-r-supercooling",
        "name": "过冷段-金属壁阻性元件",
        "inCount": {"max": 1, "min": 1},
        "outCount": {"max": 0, "min": 0},
        "icon": "heatmodule/heat-r-supercooling",
        "params": [{"name": "过冷段总长", "key": "Lssg", "value": 20},
                   {"name": "过冷段金属壁等效传热面积", "key": "Hssg", "value": 1262},
                   {"name": "过冷段金属壁传热系数", "key": "K2", "value": 30000},
                   {"name": "过冷段水位", "key": "L1", "value": "L1", "isGlobal": True},
                   ],
        "componentName": "supercoolingModule/HeatR_Supercooling",
    },

    ## 分离器
    {
        "type": "heat-r-splitter",
        "name": "分离器阻性元件",
        "inCount": {"max": 2, "min": 2},
        "outCount": {"max": 2, "min": 2},
        "icon": "heatmodule/heat-r-splitter",
        "params": [{"name": "分离耗散", "key": "eta", "value": 0.1},
                   {"name": "气体质量分数", "key": "x", "value": "x", "isGlobal": True},
                   ],
        "componentName": "spiltterModule/HeatR_Spiltter",
    },

    ## 蒸汽腔室
    {
        "type": "heat-rc-vapour",
        "name": "蒸汽腔室耗散元件",
        "inCount": {"max": 2, "min": 2},
        "outCount": {"max": 0, "min": 0},
        "icon": "heatmodule/heat-rc-vapour",
        "params": [{"name": "出口气压", "key": "P_0", "value": 100000},
                   {"name": "等效腔体体积", "key": "V_sd", "value": 100},
                   {"name": "耗散损失系数", "key": "C", "value": 1},
                   {"name": "阀门开度", "key": "Ev", "value": 0.5},
                   {"name": "蒸汽腔室出口面积", "key": "S", "value": 20},
                   {"name": "下降段水位", "key": "Ld", "value": "Ld", "isGlobal": True},
                   {"name": "过冷段水位", "key": "L", "value": "L", "isGlobal": True},
                   {"name": "饱和气体密度", "key": "rho_g_map", "isFunc": True},
                   {"name": "饱和气体比焓", "key": "h_g_map", "isFunc": True},
                   ],
        "componentName": "vapourchamberModule/HeatRC_Vapour",
    }
]

import json

with open("bondConfig.json", "w+", encoding="utf-8") as f:
    json.dump({
        "baseSystem": {
            "name": "基础键合图元件",
            "config": componentMap
            },
         "heatmodule": {
            "name": "蒸汽发生器元件",
            "config": heatMap
            }
        }, f, indent=4, ensure_ascii=False)
