#pragma checksum "..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6E21727866D57F2EDC87466E220E65A0253FA600"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WpfApp1 {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 91 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AwarenessButton;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AwarenessText;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ServiceImageButton;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ServiceImageText;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ServiceContainerButton;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ServiceContainerText;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StrategyButton;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StrategyText;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.UniformGrid DashboardTopPanel;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ImageCountText;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ContainerCountText;
        
        #line default
        #line hidden
        
        
        #line 183 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RunningDeviceCountText;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel DevicePreviewPanel;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DashboardMainPanel;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ReadDeviceInfoButton;
        
        #line default
        #line hidden
        
        
        #line 234 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DashboardRefreshButton;
        
        #line default
        #line hidden
        
        
        #line 248 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox DeviceSelector;
        
        #line default
        #line hidden
        
        
        #line 289 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas PieCanvas;
        
        #line default
        #line hidden
        
        
        #line 290 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path CpuSlicePath;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path MemorySlicePath;
        
        #line default
        #line hidden
        
        
        #line 292 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path DiskSlicePath;
        
        #line default
        #line hidden
        
        
        #line 297 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectedDeviceText;
        
        #line default
        #line hidden
        
        
        #line 303 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PieDetailText;
        
        #line default
        #line hidden
        
        
        #line 314 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CpuUsageText;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MemoryUsageText;
        
        #line default
        #line hidden
        
        
        #line 340 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DiskUsageText;
        
        #line default
        #line hidden
        
        
        #line 347 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DeviceImageGrid;
        
        #line default
        #line hidden
        
        
        #line 384 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StrategyPanel;
        
        #line default
        #line hidden
        
        
        #line 405 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StrategyReadDiskButton;
        
        #line default
        #line hidden
        
        
        #line 417 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StrategyDiskMaxSpaceText;
        
        #line default
        #line hidden
        
        
        #line 431 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox StrategyDeviceSelector;
        
        #line default
        #line hidden
        
        
        #line 450 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EdgeMemoryThresholdTextBox;
        
        #line default
        #line hidden
        
        
        #line 458 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider StrategyPercentSlider;
        
        #line default
        #line hidden
        
        
        #line 468 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StrategyPercentValueText;
        
        #line default
        #line hidden
        
        
        #line 475 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StrategyComputedThresholdText;
        
        #line default
        #line hidden
        
        
        #line 485 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid StrategyLogDataGrid;
        
        #line default
        #line hidden
        
        
        #line 512 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid StrategyImageItemsControl;
        
        #line default
        #line hidden
        
        
        #line 533 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StrategyRefreshButton;
        
        #line default
        #line hidden
        
        
        #line 543 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StrategyGenerateButton;
        
        #line default
        #line hidden
        
        
        #line 553 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StrategyDeployButton;
        
        #line default
        #line hidden
        
        
        #line 567 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ServiceImagePanel;
        
        #line default
        #line hidden
        
        
        #line 590 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ServiceImageDeviceSelector;
        
        #line default
        #line hidden
        
        
        #line 618 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel ServiceImageActionPanel;
        
        #line default
        #line hidden
        
        
        #line 619 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ServiceImageCreateButton;
        
        #line default
        #line hidden
        
        
        #line 620 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ServiceImageDownloadButton;
        
        #line default
        #line hidden
        
        
        #line 621 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ServiceImageDeployButton;
        
        #line default
        #line hidden
        
        
        #line 622 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ServiceImagePublishButton;
        
        #line default
        #line hidden
        
        
        #line 623 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ServiceImageDeleteButton;
        
        #line default
        #line hidden
        
        
        #line 653 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid SourceImageGrid;
        
        #line default
        #line hidden
        
        
        #line 688 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PreparedImageGrid;
        
        #line default
        #line hidden
        
        
        #line 740 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ProgramFileGrid;
        
        #line default
        #line hidden
        
        
        #line 765 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ServiceContainerPanel;
        
        #line default
        #line hidden
        
        
        #line 788 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ContainerDeviceSelector;
        
        #line default
        #line hidden
        
        
        #line 833 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel ContainerActionPanel;
        
        #line default
        #line hidden
        
        
        #line 852 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ContainerComposeGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.AwarenessButton = ((System.Windows.Controls.Button)(target));
            
            #line 99 "..\..\MainWindow.xaml"
            this.AwarenessButton.Click += new System.Windows.RoutedEventHandler(this.AwarenessButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 2:
            this.AwarenessText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.ServiceImageButton = ((System.Windows.Controls.Button)(target));
            
            #line 112 "..\..\MainWindow.xaml"
            this.ServiceImageButton.Click += new System.Windows.RoutedEventHandler(this.ServiceImageButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ServiceImageText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.ServiceContainerButton = ((System.Windows.Controls.Button)(target));
            
            #line 124 "..\..\MainWindow.xaml"
            this.ServiceContainerButton.Click += new System.Windows.RoutedEventHandler(this.ServiceContainerButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ServiceContainerText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.StrategyButton = ((System.Windows.Controls.Button)(target));
            
            #line 136 "..\..\MainWindow.xaml"
            this.StrategyButton.Click += new System.Windows.RoutedEventHandler(this.StrategyButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 8:
            this.StrategyText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.DashboardTopPanel = ((System.Windows.Controls.Primitives.UniformGrid)(target));
            return;
            case 10:
            this.ImageCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.ContainerCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.RunningDeviceCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.DevicePreviewPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 14:
            this.DashboardMainPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 15:
            this.ReadDeviceInfoButton = ((System.Windows.Controls.Button)(target));
            
            #line 233 "..\..\MainWindow.xaml"
            this.ReadDeviceInfoButton.Click += new System.Windows.RoutedEventHandler(this.ReadDeviceInfoButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 16:
            this.DashboardRefreshButton = ((System.Windows.Controls.Button)(target));
            
            #line 246 "..\..\MainWindow.xaml"
            this.DashboardRefreshButton.Click += new System.Windows.RoutedEventHandler(this.DashboardRefreshButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 17:
            this.DeviceSelector = ((System.Windows.Controls.ComboBox)(target));
            
            #line 258 "..\..\MainWindow.xaml"
            this.DeviceSelector.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DeviceSelector_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.PieCanvas = ((System.Windows.Controls.Canvas)(target));
            return;
            case 19:
            this.CpuSlicePath = ((System.Windows.Shapes.Path)(target));
            
            #line 290 "..\..\MainWindow.xaml"
            this.CpuSlicePath.MouseEnter += new System.Windows.Input.MouseEventHandler(this.PieSlice_OnMouseEnter);
            
            #line default
            #line hidden
            
            #line 290 "..\..\MainWindow.xaml"
            this.CpuSlicePath.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.PieSlice_OnMouseLeftButtonUp);
            
            #line default
            #line hidden
            return;
            case 20:
            this.MemorySlicePath = ((System.Windows.Shapes.Path)(target));
            
            #line 291 "..\..\MainWindow.xaml"
            this.MemorySlicePath.MouseEnter += new System.Windows.Input.MouseEventHandler(this.PieSlice_OnMouseEnter);
            
            #line default
            #line hidden
            
            #line 291 "..\..\MainWindow.xaml"
            this.MemorySlicePath.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.PieSlice_OnMouseLeftButtonUp);
            
            #line default
            #line hidden
            return;
            case 21:
            this.DiskSlicePath = ((System.Windows.Shapes.Path)(target));
            
            #line 292 "..\..\MainWindow.xaml"
            this.DiskSlicePath.MouseEnter += new System.Windows.Input.MouseEventHandler(this.PieSlice_OnMouseEnter);
            
            #line default
            #line hidden
            
            #line 292 "..\..\MainWindow.xaml"
            this.DiskSlicePath.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.PieSlice_OnMouseLeftButtonUp);
            
            #line default
            #line hidden
            return;
            case 22:
            this.SelectedDeviceText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.PieDetailText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            this.CpuUsageText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.MemoryUsageText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            this.DiskUsageText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.DeviceImageGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 351 "..\..\MainWindow.xaml"
            this.DeviceImageGrid.CellEditEnding += new System.EventHandler<System.Windows.Controls.DataGridCellEditEndingEventArgs>(this.DeviceImageGrid_OnCellEditEnding);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 366 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.DeviceImageModifyNameMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 367 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.DeviceImageModifyTagMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 368 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.DeviceImageDeleteMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 32:
            this.StrategyPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 33:
            this.StrategyReadDiskButton = ((System.Windows.Controls.Button)(target));
            
            #line 416 "..\..\MainWindow.xaml"
            this.StrategyReadDiskButton.Click += new System.Windows.RoutedEventHandler(this.StrategyReadDiskButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 34:
            this.StrategyDiskMaxSpaceText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.StrategyDeviceSelector = ((System.Windows.Controls.ComboBox)(target));
            
            #line 436 "..\..\MainWindow.xaml"
            this.StrategyDeviceSelector.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.StrategyDeviceSelector_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 36:
            this.EdgeMemoryThresholdTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 456 "..\..\MainWindow.xaml"
            this.EdgeMemoryThresholdTextBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.StrategyThresholdInput_OnChanged);
            
            #line default
            #line hidden
            return;
            case 37:
            this.StrategyPercentSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 466 "..\..\MainWindow.xaml"
            this.StrategyPercentSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.StrategyThresholdInput_OnChanged);
            
            #line default
            #line hidden
            return;
            case 38:
            this.StrategyPercentValueText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.StrategyComputedThresholdText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.StrategyLogDataGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 41:
            this.StrategyImageItemsControl = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 42:
            this.StrategyRefreshButton = ((System.Windows.Controls.Button)(target));
            
            #line 542 "..\..\MainWindow.xaml"
            this.StrategyRefreshButton.Click += new System.Windows.RoutedEventHandler(this.StrategyRefreshButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 43:
            this.StrategyGenerateButton = ((System.Windows.Controls.Button)(target));
            
            #line 552 "..\..\MainWindow.xaml"
            this.StrategyGenerateButton.Click += new System.Windows.RoutedEventHandler(this.StrategyGenerateButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 44:
            this.StrategyDeployButton = ((System.Windows.Controls.Button)(target));
            
            #line 561 "..\..\MainWindow.xaml"
            this.StrategyDeployButton.Click += new System.Windows.RoutedEventHandler(this.StrategyDeployButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 45:
            this.ServiceImagePanel = ((System.Windows.Controls.Border)(target));
            return;
            case 46:
            this.ServiceImageDeviceSelector = ((System.Windows.Controls.ComboBox)(target));
            
            #line 600 "..\..\MainWindow.xaml"
            this.ServiceImageDeviceSelector.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ServiceImageDeviceSelector_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 47:
            this.ServiceImageActionPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 48:
            this.ServiceImageCreateButton = ((System.Windows.Controls.Button)(target));
            
            #line 619 "..\..\MainWindow.xaml"
            this.ServiceImageCreateButton.Click += new System.Windows.RoutedEventHandler(this.ServiceImageActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 49:
            this.ServiceImageDownloadButton = ((System.Windows.Controls.Button)(target));
            
            #line 620 "..\..\MainWindow.xaml"
            this.ServiceImageDownloadButton.Click += new System.Windows.RoutedEventHandler(this.ServiceImageActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 50:
            this.ServiceImageDeployButton = ((System.Windows.Controls.Button)(target));
            
            #line 621 "..\..\MainWindow.xaml"
            this.ServiceImageDeployButton.Click += new System.Windows.RoutedEventHandler(this.ServiceImageActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 51:
            this.ServiceImagePublishButton = ((System.Windows.Controls.Button)(target));
            
            #line 622 "..\..\MainWindow.xaml"
            this.ServiceImagePublishButton.Click += new System.Windows.RoutedEventHandler(this.ServiceImageActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 52:
            this.ServiceImageDeleteButton = ((System.Windows.Controls.Button)(target));
            
            #line 623 "..\..\MainWindow.xaml"
            this.ServiceImageDeleteButton.Click += new System.Windows.RoutedEventHandler(this.ServiceImageActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 53:
            this.SourceImageGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 657 "..\..\MainWindow.xaml"
            this.SourceImageGrid.CellEditEnding += new System.EventHandler<System.Windows.Controls.DataGridCellEditEndingEventArgs>(this.ServiceImageGrid_OnCellEditEnding);
            
            #line default
            #line hidden
            
            #line 659 "..\..\MainWindow.xaml"
            this.SourceImageGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SourceImageGrid_OnSelectionChanged);
            
            #line default
            #line hidden
            
            #line 660 "..\..\MainWindow.xaml"
            this.SourceImageGrid.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ToggleDataGridRowSelection_OnPreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 54:
            this.PreparedImageGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 692 "..\..\MainWindow.xaml"
            this.PreparedImageGrid.CellEditEnding += new System.EventHandler<System.Windows.Controls.DataGridCellEditEndingEventArgs>(this.ServiceImageGrid_OnCellEditEnding);
            
            #line default
            #line hidden
            
            #line 694 "..\..\MainWindow.xaml"
            this.PreparedImageGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PreparedImageGrid_OnSelectionChanged);
            
            #line default
            #line hidden
            
            #line 695 "..\..\MainWindow.xaml"
            this.PreparedImageGrid.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ToggleDataGridRowSelection_OnPreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 56:
            
            #line 708 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.PreparedImageModifyNameMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 57:
            this.ProgramFileGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 746 "..\..\MainWindow.xaml"
            this.ProgramFileGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ProgramFileGrid_OnSelectionChanged);
            
            #line default
            #line hidden
            
            #line 747 "..\..\MainWindow.xaml"
            this.ProgramFileGrid.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ToggleDataGridRowSelection_OnPreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 58:
            this.ServiceContainerPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 59:
            this.ContainerDeviceSelector = ((System.Windows.Controls.ComboBox)(target));
            
            #line 798 "..\..\MainWindow.xaml"
            this.ContainerDeviceSelector.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ContainerDeviceSelector_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 60:
            this.ContainerActionPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 61:
            
            #line 834 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 62:
            
            #line 835 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 63:
            
            #line 836 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 64:
            
            #line 837 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 65:
            
            #line 838 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 66:
            
            #line 839 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 67:
            
            #line 840 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 68:
            
            #line 841 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerActionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 69:
            this.ContainerComposeGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 70:
            
            #line 866 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.ContainerModifyNameMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            System.Windows.EventSetter eventSetter;
            switch (connectionId)
            {
            case 28:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseRightButtonDownEvent;
            
            #line 361 "..\..\MainWindow.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.DeviceImageGridRow_OnPreviewMouseRightButtonDown);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 55:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseRightButtonDownEvent;
            
            #line 703 "..\..\MainWindow.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.DeviceImageGridRow_OnPreviewMouseRightButtonDown);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 71:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseRightButtonDownEvent;
            
            #line 881 "..\..\MainWindow.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.ContainerComposeGridRow_OnPreviewMouseRightButtonDown);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            }
        }
    }
}

